name: Release Tag

# 실행 조건
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
# 실행문
jobs:
  # build 라는 Naming
  build:
    # 실행 OS
    runs-on: ubuntu-latest
    # 단계별 실행
    steps:
      # Git에서 제공하는 action version
      - uses: actions/checkout@v2

      - name: 버전 정보 추출
        id: extract_version_name
        # release* 브런치 Title에서 버전 정보를 정규 표현식으로 추출 ex) 1.240725.01
        # env.VERSION으로 접근할 수 있게 $GITHUB_ENV로 저장
        run: |
          VERSION=$(echo '${{ github.event.head_commit.message }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,6}\.[0-9]{1,2}')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Release 생성
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_version_name.outputs.VERSION }}
          release_name: ${{ steps.extract_version_name.outputs.VERSION }}

          # VERSION=$(echo '${{ github.event.pull_request.title }}' | egrep -o '[0-9]{1,3}\.[0-9]{1,6}\.[0-9]{1,2}')
          # echo "VERSION=$VERSION" >> $GITHUB_ENV
